### ISSUE TITLE
Cannot install this properly

### ISSUE THREAD

**Issue by WhiteBookmark** [PaulleDemon/Email-automation#6]
Sending cold email with username/password marks the app as "Unsafe" by google.

Therefore, we need to use Google App Password instead of username/password.

For cold email this matters even more since we will be sending 40+ emails/day.

Can you make the software use app password instead of username or password in .env?

**Comment by PaulleDemon** [comment]
@WhiteBookmark I would highly recommend you to start using your own domain for cold outreach, because both Yahoo and Google has brought in couple of changes recently that prevents you from automating your emails. Would recommend using your own domain or hotmail/outlook.

One other thing, you don't really need to fill in the username and password in `.env`. Once you have your app running, you'll have to configure the email in the smtp configuration tab. 

let me know if you have any other questions.
